version: 2
jobs:
  build:
    working_directory: ~/micropost
    docker:
      - image: circleci/php:7.2.4-apache-stretch-node-browsers
        environment:
          APP_ENV: test
          DATABASE_URL: mysql://root:root@127.0.0.1/micro-post
          MAILER_FROM: micro@micropost.com
          MAILER_URL: null://localhost
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: 'root'
          MYSQL_DATABASE: micro-post
    steps:
      - checkout
      - run:
          name: Install zlib
          command: sudo apt-get install -y zlib1g-dev 
      - run:
          name: Install PHP MySQL
          command: sudo docker-php-ext-install pdo_mysql zip
      - run:
          name: Wait for MySQL
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: Composer
          command: sudo composer self-update
      - run:
          name: Composer install
          command: composer install -n --prefer-dist
      - run:
          name: Run migrations
          command: php bin/console doctrine:migrations:migrate --env=test --no-interaction
      - run:
         name: Run tests
         command: ./bin/phpunit
  deploy:
    working_directory: ~/micropost
    docker:
      - image: circleci/php:7.2.4-apache-stretch-node-browsers
        environment:
          APP_ENV: prod
          DATABASE_URL: mysql://root:root@127.0.0.1/micro-post
          MAILER_FROM: micro@micropost.com
          MAILER_URL: null://localhost
    steps: 
      - checkout
      - run:
          name: Install rsync
          command: sudo apt-get install ssh rsync
      - run:
          name: Composer install
          command: composer install -n --prefer-dist
      - run:
          name: Clear cache
          command: php bin/console cache:clear --env=prod --no-interaction
      - run:
          name: Cache warmip
          command: php bin/console cache:warmup --env=prod --no-interaction
      - run: 
          name: Yarn
          command: yarn install && yarn run encore production
      - run:
          name: Add droplet
          command: ssh-keyscan -H $DROPLET_IP >> ~/.ssh/known_hosts
      - run:
          name: Pre-deploy
          command: ssh -T $DROPLET_USER@$DROPLET_IP < bin/deploy/pre_deploy.sh
      - run:
          name: Deploy code
          command: rsync -vzcrSLhp --exclude '.env' --delete ~/micropost/ $DROPLET_USER@$DROPLET_IP:/var/www/micropost_current
      - run:
          name: Post Deploy
          command: ssh -T $DROPLET_USER@$DROPLET_IP < bin/deploy/deploy.sh
workflows:
  version: 2
  build_and_deploy: 
    jobs: 
#      - build
      - deploy:
#          requires:
#            - build
          filters:
            branches:
              only: master  

